#!/bin/bash

# This script prepares the users filesystem

GRN="\e[32m"
CLR="\e[0m"


if [[ -z "$name" ]]; then name=usersfs; fi

USERS=$(pwd)/USERS
HOME=$USERS/nodeos

sudo rm -rf $USERS &&
mkdir    -p $HOME  || exit 30


# Install /root dependencies from NPM using Ubuntu

NODE_DIR=`pwd`/../initramfs/deps/node
NPM="node $NODE_DIR/deps/npm/cli.js"
npmi="npm_config_prefix=$HOME $NPM i -g"

# Install un-commented packages
eval $npmi `grep -v "^#" packages.txt` &&
rm -rf $HOME/.npm $HOME/.node-gyp      || exit 21

cp init.js $HOME/init

#mkdir -p $HOME/etc                 &&
#cp forever-starter.json $HOME/etc/ || exit 32


#
# Wrap the system up and pack it
#

# Set files owner to nodeos user and ONLY accesible to it
sudo chown -R 1:1 "$HOME" &&
sudo chmod -R go= "$HOME" || exit 33

case $PLATFORM in
  docker)
    sudo docker build -t $name . || exit 34
  ;;
  qemu)
    USERSFS=$(pwd)/usersfs

    rm -f $name.img                      &&
    qemu-img create -f raw $name.img 32M &&
    mkfs.ext4 -F $name.img               &&

    mkdir -p $USERSFS                     &&
    sudo mount -o loop $name.img $USERSFS &&

    sudo cp -R $USERS/* $USERSFS &&

    sudo umount $USERSFS &&
    rm -r $USERSFS       || exit 35
  ;;
esac


echo -e "${GRN}Successfully built Layer-3 image '$name'${CLR}"
