#!/bin/bash

REV=$(tput rev)
BLD=$(tput bold)
GRY="\e[90m"
RED="\e[31m"
GRN="\e[32m"
WHT="\e[37m"
CLR="\e[0m"


if [[ -z "$PLATFORM" ]]; then PLATFORM=docker; fi


function err(){
  echo -e "${RED}Error Building Image${CLR}"
  exit $1
}


case $PLATFORM in
  docker)
    # if user is logged into docker index
    # automatically prefix their name to built images
    name=$(sudo docker info | grep ^Username | awk '{print $2}' )
    if [[ -z "$name" ]]; then name=local; fi

    NOSN=${name}/nodeos
  ;;
esac


# Build each layer up
(cd Layer1-linux  && PLATFORM=${PLATFORM} ./build ) &&
(cd Layer2-nodejs && PLATFORM=${PLATFORM} ./build ) &&
(cd Layer3-base   && PLATFORM=${PLATFORM} ./build ) &&
(cd Layer4-custom && PLATFORM=${PLATFORM} name=${NOSN} ./build ) || err $?

echo -e "${GRY}------------------------------------------${CLR}"
echo -e "${GRN}${BLD}Success!${CLR}"
echo -e "${GRN}You Just Built a Custom NodeOS Image ${WHT}$NOSN${CLR}"
echo -e "${GRY}------------------------------------------${CLR}"
echo
echo -e "- Interactively run your image with:"

case $PLATFORM in
  docker)
    echo -e "${WHT}    sudo docker run -t -i $NOSN${CLR}"
    echo
    echo -e "- Share your creation with:"
    echo -e "${WHT}    sudo docker push $NOSN${CLR}"
  ;;
  qemu)
    echo -e "${WHT}    sudo qemu-system-i386 --kernel /vmlinuz --initrd Layer3-base/layer3.cpio.gz -hda Layer4-custom/layer4.img -enable-kvm -nographic -append \"console=ttyS0 /bin/nodeos-boot /dev/sda\"${CLR}"
  ;;
esac
