#!/bin/bash

NAME=$(sudo docker info | grep ^Username | awk '{print $2}' )
if [[ -z "$NAME" ]]; then NAME=local; fi

NOSN=${NAME}/nodeos

(cd Layer1-linux  && sudo name=layer1 ./build -f ) &&
(cd Layer2-nodejs && sudo name=layer2 ./build )    &&
(cd Layer3-base   && sudo name=layer3 ./build )    || exit 10

sudo docker tag layer3 nodeos/nodeos               || exit 20

(cd Layer4-custom && sudo name=${NOSN} ./build )   || exit 30

