#!/usr/bin/env node

var resolve = require('path').resolve

var publishRelease = require('publish-release')


const token = process.env.GITHUB_TOKEN
if(!token)
  return console.error('GITHUB_TOKEN environment variable is not defined')


var opts =
{
  token: token,
  owner: 'NodeOS',
  repo: 'NodeOS',
  tag: Date.now().toString(),
  prerelease: true,
  assets:
  [
    'out/i386-pc_image.zip',
    'out/i386-pc_qemu.zip',
    'out/nocona-pc_image.zip',
    'out/nocona-pc_qemu.zip'
  ]
}

publishRelease(opts, function(error)
{
  if(error) console.error(error)
})
