#!/bin/bash

# Prepare a minimal ROOT filesystem with some basic commands and configs

GRN="\e[32m"
CLR="\e[0m"


if [[ -z "$name" ]]; then name=layer1; fi

case $PLATFORM in
  docker)
    ROOT=$(pwd)/ROOT
  ;;
  qemu)
    ROOT=/tmp/ROOT
  ;;
esac


rm    -rf $ROOT &&
mkdir -p  $ROOT || exit 10


COREUTILS_VERSION=8.23
COREUTILS_URL=http://ftp.gnu.org/pub/gnu/coreutils/coreutils-$COREUTILS_VERSION.tar.xz

# Download and compile coreutils. We are only interested on 'env', thought.
if [[ ! -d deps/coreutils ]]; then
  sudo apt-get install autopoint bison gperf texinfo                     &&
  mkdir -p deps/coreutils                                                &&
  curl $COREUTILS_URL | tar xJf - -C deps/coreutils --strip-components=1 &&
  ( cd deps/coreutils && ./configure && make --jobs=16 )                 || exit 11
fi

# For now, lets copy /usr/bin/env because of how deeply node.js depend on it
mkdir -p $ROOT/usr/bin                         &&
cp    -f deps/coreutils/src/env $ROOT/usr/bin/ || exit 12


# Use a well-known DNS server for now, we do not yet support DHCP
mkdir -p $ROOT/etc              &&
cp    -f resolv.conf $ROOT/etc/ || exit 13


# Wrap the system up and pack it
case $PLATFORM in
  docker)
    tar -cC $ROOT . | sudo docker import - $name || exit 14
  ;;
esac

echo -e "${GRN}Successfully built Layer-1 image '$name'${CLR}"
