#!/bin/bash

# Prepare a minimal ROOT filesystem with some basic commands and configs


if [[ -z "$name" ]]; then name=layer1;    fi
if [[ -z $ROOT ]];   then ROOT=/tmp/ROOT; fi


## Require root privileges for some operations
#if [[ $(id -u) -ne 0 ]]; then
#    echo "Please Run as Root"
#    exit 10
#fi


# If -f is specified, overwrite the previous build
if [[ "$1" == "-f" ]]; then
  rm -rf $ROOT
fi

if [[ -d $ROOT ]]; then
  echo "Please Delete $ROOT - Build Directory Exists"
  echo "To Force Overwriting Use -f"
  exit 11
fi


# For now, lets copy /usr/bin/env because of how deeply node.js depend on it
mkdir -p $ROOT/usr/bin               &&
cp    -f /usr/bin/env $ROOT/usr/bin/ || exit 12

# Use a well-known DNS server for now, we do not yet support DHCP
mkdir -p $ROOT/etc              &&
cp    -f resolv.conf $ROOT/etc/ || exit 13


# Wrap the system up and pack it
case $PLATFORM in
  docker)
    tar -cC $ROOT . | docker import - $name || exit 14
  ;;
esac

echo "Successfully built Layer-1 image '$name'"
