# Autogenerated by `npm run dockerBuild`

# NodeOS
#
# Copyright (c) 2013-2017 Jacob Groundwater, Jesús Leganés-Combarro 'piranna'
# and other contributors
#
# MIT License

FROM nodeos/initramfs

MAINTAINER Jesús Leganés Combarro 'piranna' <piranna@gmail.com>

VOLUME /tmp
ADD usersfs.tar.gz /tmp/

ENV root container

ENTRYPOINT ["/init"]
