#!/usr/bin/env bash


PLATFORM=iso_32    npm install || exit $?
PLATFORM=iso_64    npm install || exit $?
PLATFORM=qemu_32   npm install || exit $?
PLATFORM=qemu_64   npm install || exit $?
#PLATFORM=raspberry npm install || exit $?
