#!/usr/bin/env bash


PLATFORM=iso_32    npm install --no-spin || exit $?
PLATFORM=iso_64    npm install --no-spin || exit $?
PLATFORM=qemu_32   npm install --no-spin || exit $?
PLATFORM=qemu_64   npm install --no-spin || exit $?
#PLATFORM=raspberry npm install --no-spin || exit $?
PLATFORM=vagga_32  npm install --no-spin || exit $?
PLATFORM=vagga_64  npm install --no-spin || exit $?
