#!/usr/bin/env sh

docker run -it                         \
    --cap-add SYS_ADMIN                \
    --security-opt=apparmor:unconfined \
    --device /dev/fuse                 \
    nodeos/nodeos
#    -v usersfs:/tmp                    \
