#!/usr/bin/env bash

REV=$(tput rev)
BLD=$(tput bold)
GRY="\e[90m"
RED="\e[31m"
GRN="\e[32m"
WHT="\e[37m"
CLR="\e[0m"


TOOLCHAIN=`pwd`/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain

source $TOOLCHAIN/scripts/adjustEnvVars.sh || exit $?


case $PLATFORM in
  docker)
    # if user is logged into docker index
    # automatically prefix their name to built images
    name=$(docker info | grep ^Username | awk '{print $2}' )
    if [[ -z "$name" ]]; then name=local; fi

    NOSN=${name}/nodeos
  ;;
esac

export PLATFORM


## Build each layer up
#(cd node_modules/nodeos-cross-toolchain              npm install ) &&
#(cd node_modules/nodeos-barebones                    npm install ) &&
#(cd node_modules/nodeos-initramfs                    npm install ) &&
#(cd node_modules/nodeos-rootfs                       npm install ) &&
#(cd node_modules/nodeos-usersfs         name=${NOSN} npm install ) || err $?


if [[ ! -z "$RELEASE" ]]; then
  OUT_DIR=`pwd`/out/$CPU_FAMILY
  ZIP_FILE=$OUT_DIR-$PLATFORM.zip

  mkdir -p `dirname $OUT_DIR`
  rm -f $ZIP_FILE

  case $PLATFORM in
    pc_qemu)
      zip -j $ZIP_FILE                                  \
        node_modules/nodeos-barebones/bzImage           \
        node_modules/nodeos-initramfs/initramfs.cpio.gz \
        node_modules/nodeos-usersfs/usersfs.img         || exit 10

      eval "echo -e \"$(< runners/qemu.sh)\"" > /tmp/run.sh
    ;;
    pc_image)
      zip -j $ZIP_FILE                          \
        node_modules/nodeos-rootfs/rootfs.img   \
        node_modules/nodeos-usersfs/usersfs.img || exit 11

      eval "echo -e \"$(< runners/image.sh)\"" > /tmp/run.sh
    ;;
  esac

  chmod +x /tmp/run.sh
  zip -j $ZIP_FILE /tmp/run.sh || exit 12

  zip -j $ZIP_FILE runners/README.md || exit 13
fi


echo -e "${GRY}------------------------------------------${CLR}"
echo -e "${GRN}${BLD}Success!${CLR}"
echo -e "${GRN}You Just Built a Custom NodeOS Image ${WHT}$NOSN${CLR}"
echo -e "${GRY}------------------------------------------${CLR}"
echo
echo -e "- Interactively run your image with:"

case $PLATFORM in
  docker)
    echo -e "${WHT}    docker run -t -i $NOSN${CLR}"
    echo
    echo -e "- Share your creation with:"
    echo -e "${WHT}    docker push $NOSN${CLR}"
  ;;
  pc_qemu|pc_image|raspberry_qemu)
    echo -e "${WHT}    npm start${CLR}"
  ;;
esac
