#!/usr/bin/env bash

REV=$(tput rev)
BLD=$(tput bold)
GRY="\e[90m"
RED="\e[31m"
GRN="\e[32m"
WHT="\e[37m"
CLR="\e[0m"


if [[ -z "$PLATFORM" ]]; then PLATFORM=docker; fi


function err(){
  echo -e "${RED}Error Building Image${CLR}"
  exit $1
}


case $PLATFORM in
  docker)
    # if user is logged into docker index
    # automatically prefix their name to built images
    name=$(docker info | grep ^Username | awk '{print $2}' )
    if [[ -z "$name" ]]; then name=local; fi

    NOSN=${name}/nodeos
  ;;
esac


# Build each layer up
(cd node_modules/nodeos-barebones && PLATFORM=${PLATFORM} ./build ) &&
(cd node_modules/nodeos-initramfs && PLATFORM=${PLATFORM} ./build ) &&
(cd node_modules/nodeos-rootfs    && PLATFORM=${PLATFORM} ./build ) &&
(cd node_modules/nodeos-usersfs   && PLATFORM=${PLATFORM} name=${NOSN} ./build ) || err $?

echo -e "${GRY}------------------------------------------${CLR}"
echo -e "${GRN}${BLD}Success!${CLR}"
echo -e "${GRN}You Just Built a Custom NodeOS Image ${WHT}$NOSN${CLR}"
echo -e "${GRY}------------------------------------------${CLR}"
echo
echo -e "- Interactively run your image with:"

case $PLATFORM in
  docker)
    echo -e "${WHT}    docker run -t -i $NOSN${CLR}"
    echo
    echo -e "- Share your creation with:"
    echo -e "${WHT}    docker push $NOSN${CLR}"
  ;;
  qemu)
    echo -e "${WHT}    npm start${CLR}"
  ;;
esac
