#!/usr/bin/env node

var readdir = require('fs').readdir

var upload = require('prebuild/upload')


const PREBUILDS = 'prebuilds'

const PKG = require('../package.json')

const token = process.env.GITHUB_TOKEN
if(!token) throw 'GITHUB_TOKEN environment variable is not defined'

const prerelease = (new Date()).toISOString().substr(0,10)

var branch_name = process.env.BRANCH_NAME
if(branch_name && branch_name !== 'master') prerelease += '.'+branch_name

readdir(PREBUILDS, function(err, files)
{
  if(err) throw err

  var opts =
  {
    upload: token,
    pkg: PKG,
    prerelease: prerelease,
    files: files.map(function(file){return PREBUILDS+'/'+file})
  }

  upload(opts, function(error)
  {
    if(error) throw error
  })
})
