#!/usr/bin/env node

var fs = require('fs');

var spawn = require('child_process').spawn


var cpu = fs.readlinkSync('node_modules/nodeos-barebones/bzImage').split('/');

var cpu_family;
switch(cpu[cpu.length-2])
{
  case 'armv6':
    cpu_family = 'arm'
  break

  case 'i386':
  case 'i486':
  case 'i586':
  case 'i686':
  case 'i786':
    cpu_family = 'i386'
  break

  case 'nocona':
  case 'x86_64':
    cpu_family = 'x86_64'
  break
}

var append = 'root=/dev/sda'
var graphicFlag

switch(process.argv[2])
{
  case 'nographic':
    append += ' console=ttyS0'
    graphicFlag = 'nographic'
  break

  case 'curses':
    append += ' vga=extended'  // 80x50
    graphicFlag = 'curses'
  break

  default:
    append += ' vga=0x318'  // 1024x768x24
}

var command = 'qemu-system-'+cpu_family

var args =
[
  '-enable-kvm',
  '--kernel', 'node_modules/nodeos-barebones/bzImage',
  '--initrd', 'node_modules/nodeos-initramfs/initramfs.cpio.gz',
  '-hda',     'node_modules/nodeos-usersfs/usersfs.img',
  '-append',  append
]

if(graphicFlag)
  args.push('-'+graphicFlag)

// check if kvm is supported
var kvm = /(vmx|svm)/;
var contents = "";

try
{
  contents = fs.readFileSync('/proc/cpuinfo');
} catch(e){
  throw(e);
}

if(kvm.test(contents) === false)
{
  // disable kvm
  console.log("Your computer does not support kvm.  NodeOS will be slower without it.");
  args.shift();
}

spawn(command, args, {stdio: 'inherit'})
.on('error', console.trace.bind(console));
