#!/bin/bash

if [[ $(id -u) -ne 0 ]]; then
    echo "Please Run as Root"
    exit 20
fi

if [[ -e "$SUDO_COMMAND" ]]; then SUDO="sudo "; fi
if [[ -z "$name" ]]; then
  echo "Please Specify an Image Name"
  echo "e.g. '${SUDO}name=<MY_NAME>/nodeos $0 $@'"
  exit 5
fi

docker build -t $name . || exit 10

