#!/bin/bash

# This script prepares the users filesystem

GRN="\e[32m"
CLR="\e[0m"


if [[ -z "$name" ]]; then name=layer4; fi

USERS=$(pwd)/USERS
HOME=$USERS/root

rm    -rf $USERS &&
mkdir -p $HOME   || exit 40


# Install /root dependencies from NPM using Ubuntu

NODE_DIR=`pwd`/../Layer2-nodejs/deps/node
NPM="$NODE_DIR/node $NODE_DIR/deps/npm/cli.js"
npmi="npm_config_prefix=$HOME $NPM i -g"

# Install un-commented packages
eval $npmi `grep -v "^#" packages.txt` || exit 41

ln -sf bin/forever-starter $HOME/init


mkdir -p $HOME/etc                 &&
cp forever-starter.json $HOME/etc/ || exit 42


case $PLATFORM in
  docker)
    sudo docker build -t $name . || exit 43
  ;;
  qemu)
    rm -f $name.img
    qemu-img create -f raw $name.img 48M
    mkfs.ext4 -F $name.img

    mkdir /tmp/usersfs
    sudo mount -o loop $name.img /tmp/usersfs

    # sudo mkdir /mnt/rootfs/boot
    # sudo cp vmlinuz /mnt/rootfs/boot/vmlinuz
    # sudo cp initrd /mnt/rootfs/boot/initrd

    sudo cp -R $USERS/* /tmp/usersfs

    sudo umount /tmp/usersfs
    rm -r /tmp/usersfs
  ;;
esac

echo -e "${GRN}Successfully built Layer-4 image '$name'${CLR}"
